spring:
  datasource:
    url: jdbc:mysql://localhost:3306/watch?useSSL=false
    username: root
    password: root
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
app:
  datasource:
    jdbc-url: jdbc:mysql://localhost:3306/watch?useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  front-domain: http://localhost:8080
  api-domain: http://localhost:8080
  allowed-origins: http://localhost:8080
  cookie:
    domain: localhost
logging:
  level:
    '[com.datn.watch]' : debug
  charset:
    console: utf-8

server:
  port: 8080
  error:
    whitelabel:
      enabled: true
  servlet:
    session:
      timeout: 18000
      cookie:
#        domain: watch.com.vn
        domain: localhost
        name: JSESSIONID
        same-site: none
        secure: true